language: node_js
sudo: false
node_js:
  - '8'
cache:
  apt: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
before_install:
  - git config --global user.name "tianyong90"
  - git config --global user.email 412039588@qq.com
script:
  - npm install -no-optional
