language: node_js
sudo: false
node_js:
  - '7'
cache:
  apt: true
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  ssh_known_hosts: github.com
before_install:
  - openssl aes-256-cbc -K $encrypted_0231095cfdaa_key -iv $encrypted_0231095cfdaa_iv -in ./travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "tianyong90"
  - git config --global user.email 412039588@qq.com
script:
  - npm install -no-optional
after_success:
  - ssh $ssh_user@$ssh_host
  - cd /data/wwwroot
  - git checkout master -f
  - git fetch origin
  - git reset --hard origin/master
  - npm run dist
